[project]
name = "my-work"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-restful>=0.3.10",
    "python-dotenv>=1.1.1",
    "sqlalchemy>=2.0.42",
    "telebot>=0.0.5",
]
